### ISSUE TITLE
Access to Development SAS servers

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#104]
As discussed during a meeting, we would like to get access to a development instance of a SAS server from a SAS provider/s.

This process might take some time according to Joey.

**Comment by xbend** [comment]
@jpad-freedomfi 
Could you please paste here the URL to the dev/prod SAS server for which we have the certs?

**Comment by jpad-freedomfi** [comment]
@xbend https://spectrum-connect.federatedwireless.com/v1.2/
