### ISSUE TITLE
Verify SAS interface with test suite

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#11]
DP Requirement ID: **SCI-04**

The SAS client interface shall comply with all interface test cases defined in [2].

[2]
SSC-Wireless Innovation Forum, “Test and Certification for Citizens Broadband Radio Service (CBRS); Conformance and Performance Test Technical Specification; CBSD/DP as Unit Under Test (UUT)”, WINNF-TS-0122-V1.x.x Test and Certification for Citizens Broadband Radio Service (CBRS); Conformance and Performance Test Technical Specification; CB

**Comment by tjj-freedomfi** [comment]
There are dependencies in the WINNF test suite that are >50GB big - @jpad-freedomfi & @m-trojanowski will work on picking a subset of tests (i.e. excluding those aiming to test SAS itself) that don’t need those dependencies

**Comment by xbend** [comment]
Put on hold. This requires a lot of work on the CI code and on the WINNFs testing harness (which is not really supposed to be run in an automated fashion). Testing harness and WINNF 0122 should be done manually.

**Comment by tjj-freedomfi** [comment]
as per @jpad-freedomfi - closing with NoFix
