### ISSUE TITLE
[Spike] Create a flow of events and reactions for TR069 CBSDs 

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#116]

**Comment by jpad-freedomfi** [comment]
First draft of happy path flow produced. Attached here. Will be discussed 6/24 with @Amar and @xbend [https://app.zenhub.com/files/351498663/88fdaf6e-f1cd-4e28-8eba-8fa6253a01a2/download](https://app.zenhub.com/files/351498663/88fdaf6e-f1cd-4e28-8eba-8fa6253a01a2/download)
