### ISSUE TITLE
Implement TCP_NODELAY for SAS client interface

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#12]
DP Requirement ID: **SCI-05**

The SAS client interface shall be implemented with a **TCP_NODELAY** socket so that no extra queuing delay is added between the application and the wire.

**Comment by xbend** [comment]
SAS-facing client application (currently configuration_controller, later on a separate microservice) is using python 3 library `requests` which is using `urllib3` underneath. `urllib3` sets the TCP_NODELAY flag on the connection socket by default ((https://github.com/urllib3/urllib3/blob/main/src/urllib3/connection.py#L112)
