### ISSUE TITLE
Full magma environment setup and installation

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#122]
For development and testing purposes of DP interactions with Magmas `enodebd`, we will require a full test installation of Magma (Orchestrator + Access Gateway).

This will require:
- [x] installation of Magmas ocr8r in Lab/Cloud
- [x] installation of Magmas AGW in Lab
- [x] hooking up a Biacells device to the AGW in Lab
- [x] setting up usable connection to the setup with all credentials, routes, jumps, etc (ideally we want each developer to have this set up via 'make' or some other mechanism)

**Comment by m-trojanowski** [comment]
#141
