### ISSUE TITLE
Implement "Active Mode" in DP

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#129]
As part of this task, please implement functionality defined in the spike, to handle a new TR069 device and initiate communication with SAS on its behalf.

Please also include additions to existing python services (like extension of RC API, etc)

Also please revise the existing stories/tasks that are already on the board regarding Active Mode, and connect them to this issue as possible subtasks/clarifications.

**Comment by WojSad** [comment]
worklog: https://docs.google.com/document/d/1BVzCU7ymE2rFUzZaYzBT4aAltC4L0a0-c4TNK2oh46s/edit
