### ISSUE TITLE
Capture TR069 Traffic between Baicells 436Q and its own DP

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#135]
To help us with spikes and development, we would like to capture raw TR069 traffic/messages sent between Baicells 436Q and its own DP.

**Comment by jpad-freedomfi** [comment]
File attached. [https://app.zenhub.com/files/351498663/12fc36de-4f06-4e67-ae11-59d9ba8fc8c7/download](https://app.zenhub.com/files/351498663/12fc36de-4f06-4e67-ae11-59d9ba8fc8c7/download)

**Comment by jpad-freedomfi** [comment]
@xbend let me know if you need more captures. Setup is now in place so future captures are no problem.

**Comment by xbend** [comment]
@jpad-freedomfi 
Could you please extend the capture with more scenarios done on the radio side.

We would like to see some more parameters flying between enb and internal DP.

**Comment by jpad-freedomfi** [comment]
Updated capture linked here:

https://drive.google.com/file/d/1A-H3byzwXZ7eGzN04e90yfPz3zz_CYif/view?usp=sharing 

I did the following actions via ACS:

Changed power 7:14

Changed preferred frequency list 7:18

Downtilt, azimuth, height 7:22

Gain, beam width 7:25

timstamps approximate. Any other reboots etc. were automatically done. I just did the change above, hit "OK" and waited.
