### ISSUE TITLE
Add automated horizontal scaling

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#15]
DP Requirement ID: **DA-02**

The DP shall be horizontally scalable based on the number of connections/CBSDs. 

- [x] prepare k8s infrastructure (3 SPs)
- [ ] review the code and adjust for scaling purposes (~2 SPs)

**Comment by m-trojanowski** [comment]
#96

**Comment by xbend** [comment]
Further development of scaling code depends on the decision regarding multiple sas support.
It was agreed on 16.06.2021 with Joey that it should be OK that multiple CC instances will only process their own request batches and send those batches separately towards SAS as individual request bundles.

however multiple sas support will require redesign of the fetch logic
