### ISSUE TITLE
[MVP] Migrate DP to Magma

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#155]
LTE <> DP modules
* Modules hierarchy: https://magma.github.io/magma/docs/next/orc8r/dev_dependencies
* Plan is to utilize a separate DP module for the functionality that is specific to the DP domain
* DP module will depend on LTE module, out of architectural necessity ( I.e. new module hierarchy will be DP -> LTE -> Orc8r)

Orc8r DP module
* Straightforward, standalone K8s pods-backed services providing Orc8r targets for DP-enabled AGWs
* Any number of services in the DP module is acceptable, especially for MVP, though preference for monolithic services
* dp/gateway will contain no new services
* dp/protos will contain the relevant protos for DP-domain data models and Orc8r<>AGW interface
* dp/cloud will contain the DP-relevant Orc8r services

Current list of subtasks:
- [x] Migrate DP code into proposed directory structure (in magma, this will be `dp/cloud` and `dp/protos`)
- [x] Adjust the code to the new dir structure and ensure that Unit tests run locally
- [x] Integrate Magma's DP with all essential services (at this point it seems its only psql database)
- [x] Ensure that Magma's Postgresql as a DP database provisioned
- [x] Add possibility of local development on EKS cluster
- [x] Test orc8r deployment **with** dp (have DP services actually be deployed as part of orc8r)
- [x] Unit tests for DP pass in CI
- [x] Integration tests for DP pass in Magma environment (this will also require a spike to see how this could actually be done)
  - [x] Prepare job to deploy/update orc8r on AWS
  - [x] Prepare code to build and upload docker containers for orc8r
  - [x] Update helm chart to receive traffic from enodebd
  - [x] Prepare job to deploy/update dp on AWS
  - [x] Prepare job to upload helm chart to helm repository
  - [x] Prepare code to open reverse ssh tunnel to agw, during deployment job.
  - [x] Prepare code to deploy/update enodebd code on agw.
  - [x] Prepare code/job to run integration tests.
  - [x] Prepare code/job to collect integration tests results.

**Comment by xbend** [comment]
There is a complication regarding the migration.
It appears that we will not be able to deploy magmas "master" on FreedomFi lab (requires confirmation from FreedomFi).

Development workflow of:
1. Develop into Magmas Community "master" and merge
2. Cherry-pick from Magmas master into development branch of FreedomFi magma fork
appears to be very time consuming and not trivial.

This task will re re-estimated and planned after Sprint Review session.

**Comment by m-trojanowski** [comment]
https://github.com/openEPC/magma/pull/19

**Comment by tjj-freedomfi** [comment]
Adding a sub-task for the possibility of local development on EKS cluster (~2 SPs)

**Comment by tjj-freedomfi** [comment]
[Joey] For the DB objects creation let's try to use a user with the privileges limited to DP objects only to narrow possible damage if something goes wrong

**Comment by m-trojanowski** [comment]
Running integration tests on eks in Jenkins:
https://jenkins.freedomfi.com/job/domain_proxy/job/dp-integration-tests/job/main
