### ISSUE TITLE
Generate FreedomFI FCC certs

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#156]

**Comment by m-trojanowski** [comment]
First certificate for cc-sas was created, with guidance to this document:
https://www.wirelessinnovation.org/assets/work_products/Specifications/winnf-17-s-0022%20v1.0.0%20cbrs%20pki%20certificate%20policy.pdf

**Comment by m-trojanowski** [comment]
I'm gonna put into blocked until we're gonna have a physical radio to continue tests, so we can issue second cert.

**Comment by xbend** [comment]
The DP<->SAS certificate pair was created and tested to be working.
Full completion of the task will require us to generate a certificate pair for the Ingres side of DP (so facing a CBRS radio).

We currently do not have any radio that talks directly in CBRS-SAS protocol.

**Comment by xbend** [comment]
New Certificates have been generated and old certs were revoked.

Because of an issue with SSL on the SAS server side, keeping this in Review until we are certain that the issue is not caused by the new certs.
