### ISSUE TITLE
DP solution should be self-contained

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#16]
DP Requirement ID: **DA-03**

The DP shall be self contained such that it is deployable in any standard kubernetes environment including:
- [x] On premises x86 compute platform (specs TBD)
- [x] AWS EKS

**Comment by jpad-freedomfi** [comment]
@m-trojanowski Should this include VMware platform? 

Also the checkboxes don't show checked. is that just administrative detail or are those tasks not completed?

**Comment by m-trojanowski** [comment]
#119

**Comment by tjj-freedomfi** [comment]
As per discussion with Boris today - let's close 'On premises x86 compute platform (specs TBD)' part as Won't fix
