### ISSUE TITLE
Adopt DP integration tests into Magma Integration tests flow

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#160]
The original plan for integrating DP tests into magma CI was to run those tests as they were run, when DP was in a separate repo.
CI will create a replica of former DP infra (including Postgres instance) and run tests that way.

In this task, we would like to run the integration tests the same way as Magma is doing.

**Comment by tjj-freedomfi** [comment]
duplicate with #155, closing as Won't Fix
