### ISSUE TITLE
Write examples for converting SAS EIRP to Baicells reference signal power TR069 object

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#166]

**Comment by jpad-freedomfi** [comment]
Here is an example. I realized while doing, we have to account for antenna gain. EIRP includes antenna gain, I believe Reference Signal Power is conducted value. In first example, I have use 0 dBi antenna (perfect isotropic). In 2nd example I have 12dBi antenna gain as example. [https://app.zenhub.com/files/351498663/cfcdb354-9449-401f-9fa0-93b8562b2b86/download](https://app.zenhub.com/files/351498663/cfcdb354-9449-401f-9fa0-93b8562b2b86/download)
