### ISSUE TITLE
[spike] Define backend for frontend scope for the epic definition

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#170]

**Comment by jkmar** [comment]
Document with questions: https://docs.google.com/document/d/1LE7T_U2SpZziqr03pzwtTqb1VhxL3u7mBDbFCnazUD0/edit#
Still more meeting are needed to define a scope, also knowledge transfer about magma API is necessary.

**Comment by xbend** [comment]
Analysis of scope done. Document created: https://docs.google.com/document/d/177GQSus-chF_Hgv2ZrN77vWOnWM4LnWfxJJx8nINnWU/edit#

Option C chosen as epic definition and High Level scope of work.
