### ISSUE TITLE
FCC cert revoke and reissue

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#185]
Add mechanism to prevent future secret leaks.

**Comment by m-trojanowski** [comment]
support ticket was created. However it had to be created on Joey email address.

**Comment by xbend** [comment]
Old certificates are now revoked and are no longer accepted by production SAS.

Please generate new certs.

**Comment by xbend** [comment]
Because of SSL issue from SAS server side, we are not 100% sure that the problem is not related to newly generated certs OR the revoke process.

SAS support engaged.

**Comment by xbend** [comment]
Problem found.
The issue was that we were not sending a complete cert chain when presenting the cert to the server.
