### ISSUE TITLE
CBSD proxy should be a pluggable module

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#21]
DP Requirement ID: **CPI-03**

The CBSD proxy interface shall be implemented as a pluggable module to internal APIs such that other external interface protocol modules (TR-069, SNMP, NETCONF) can be supported in parallel to the SAS client interface defined in [1] on a per connection basis. 

[1]
SSC-Wireless Innovation Forum, “Signaling Protocols and Procedures for Citizens Broadband Radio Service (CBRS): Spectrum Access System (SAS) - Citizens Broadband Radio Service Device (CBSD) Interface Technical Specification”, WINNF-TS-0016-V1.x.x https://winnf.memberclicks.net/assets/CBRS/WINNF-TS-0016.pdf

**Comment by xbend** [comment]
Please check of detection of simple HTTP (CBSD-SAS) and TR069 is possible - for example by analysing HTTP headers.
That way gateway could redirect traffic based on that detection.

**Comment by xbend** [comment]
Discussed with Joey and shifted this task to sprint Sprint: Jul 5 - Jul 25, due to delayed caused by `enodebd` discussions and planning.
