### ISSUE TITLE
Implement TCP_NODELAY for CBSD proxy interface

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#22]
DP Requirement ID: **CPI-04**

The CBSD proxy interface shall be implemented with a TCP_NODELAY socket so that no extra queuing delay is added between the application and the wire.

**Comment by tjj-freedomfi** [comment]
to be checked if in the implementations we're aiming at (Contour, nginx) it's possible to limit setting the flat for particular services

**Comment by tjj-freedomfi** [comment]
due to changed architecture sketch - moved to the next sprint

**Comment by m-trojanowski** [comment]
Rergarding contour/envoy tandem. TCP_NODELAY flag is set by default inside envoy.
[Link to source code: nodelay function call setup](https://github.com/envoyproxy/envoy/blob/main/source/common/http/codec_client.cc#L44)

[Link to source code: nodelay function](https://github.com/envoyproxy/envoy/blob/main/source/common/network/connection_impl.cc#L264)

**Comment by xbend** [comment]
Check/Add same thing for nginx ingress.

**Comment by m-trojanowski** [comment]
#111
