### ISSUE TITLE
Create new orc8r environment on AWS

### ISSUE THREAD

**Issue by m-trojanowski** [magma/domain-proxy#229]
As stated @xbend needs extra env for testing purposes

**Comment by m-trojanowski** [comment]
AGW connection is on hold until new environment will be required

**Comment by xbend** [comment]
Reminder:
Make sure DP and orc8r use the same db (connection string)

**Comment by m-trojanowski** [comment]
Two Bugs found.
dp
 protocol_controller
    tlsConfig:
      paths: {}
and
https://github.com/openEPC/magma/blob/master/dp/cloud/helm/dp/charts/domain-proxy/templates/protocol_controller/service.yaml#L1

**Comment by m-trojanowski** [comment]
https://github.com/openEPC/magma/pull/84
