### ISSUE TITLE
Create testing environment on AWS for certification

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#245]
We should prepare a testing machine on FreedomFi AWS cluster with a prepared environment for controlling the testing environment during certification process.

- [x] Create new VM on AWS cluster with Ubuntu (20.04 preferred)
- [x] Create new AWS user to be used to authorize with `aws` toolset for accessing the AWS cluster from that environment
- [x] Add SSH keys to authorized so that a few users can log in
- [x] Prepare the system for performing testing environment setup
- [x] Install necessary tools (make, helm)
- [x] Setup docker to be usable by default user
- [x] Download magma repo from openEPC and set correct branch `certification_process`
- [x] Do test deployment of DProxy with Testing Harness, register an existing radio and see if the flow works
- [x] Update documentation (https://docs.google.com/document/d/1tNaMZAEsbGaqkQvJGS1Ffsio7eXy_GlZm499E0nMXeI) with "how to run a test" steps
- [ ] Verify with Joey that the env is usable

**Comment by m-trojanowski** [comment]
Vm prepare, @xbend please have a look
