### ISSUE TITLE
[spike] Integration tests for dp orc8r service and dp

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#251]
Example flow: (most likely better to split it into multiple tests, order also might be different)
1. Send create cbsd http request to orc8r
2. Send grpc request to radio controller on behalf of enodebd. (possibly optional, maybe this should be first)
3. Send fetch cbsd http request to orc8r and check if there are grants
4. Send grpc request to radio controller on behalf of enodebd and check if transmission is enabled
5. Send delete cbsd http request to orc8r
6. Send fetch cbsd http request to orc8r and check if there is and not found error
7. Send grpc request to radio controller on behalf of enodebd and check if transmission is disabled
8. Send get logs request to orc8r and check domain proxy logs

The idea is to use existing test_runner service in DP for those integration tests. But this issue needs to be consulted with Community, therefore scope is unknown, depends on the outcome of the Community discussion.

**Comment by xbend** [comment]
No community feedback. Not to stall the development, we are proceeding with integration tests development using our own known `test_runner` approach.
