### ISSUE TITLE
Rebase with newest magma

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#254]
- [ ] remove symlinks to certs and modify gitignore

**Comment by xbend** [comment]
Amount of work depends on the state of Magma master, problems during rebase, and complications after rebase during deployment and field testing.
Pessimistic estimate at 8.

**Comment by xbend** [comment]
Would be good to run integration tests after rebase.

**Comment by xbend** [comment]
Make sure that symlinks to certs are removed and gitignore added to not stage changes to helm cert directories
