### ISSUE TITLE
[spike] Deploy swagger definitions on swagger hub

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#260]
Investigate how to make new DP swagger definitions be part of the autogenerated combined Magma Core swagger available at:
https://app.swaggerhub.com/apis/MagmaCore/Magma/1.0.0#/

**Comment by m-trojanowski** [comment]
Resolution:
On pushes to master or release branches github triggers job called `cloud-upload` (in `.github/workflows/build_all.yaml` file) which in turns upload file 
`orc8r/cloud/go/obsidian/swagger/v1/swagger.yml` to swagger hub. Mentioned file is generated during controller docker build, which we already updated. This means that once we will push our changes they will be updated in swaggerhub. 
This concludes this spike.
