### ISSUE TITLE
Remove created_data and updated_date fields

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#262]

**Comment by xbend** [comment]
We have decided that for the time being, the inclusion of date fields is not that important to be worked on for removal.
We will most likely move our data model to the orchestrator's `configuration` eventually, which will be an extensive refactoring task anyway.

The datetime fields are currently handled in a sufficient way and do not cause any business logic problems.

Deciding to mark as `WONT IMPLEMENT`.
