### ISSUE TITLE
Implement CBSD messages proxying

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#3]
DP Requirement ID: **SCI-02**

- [x] [Dysproz, WojSad] The SAS client interface shall be compliant with [1] when sending the following messages on behalf of proxied CBSDs:
- Registration Request
- Spectrum Inquiry Request
- Grant Request
- Heartbeat Request
- CBSD Measurement Report
- Relinquishment Request
- Deregistration Request
- [x] [WojSad] Implement Python class for communicating with SAS interface
- [x] [Dysproz] Spike solution with routing requests based on topics
- [x] [Dysproz] Implement Python class which handles multiple queues with different requests topics
- [x] [Dysproz] Implement merging mechanism for multiple requests with the same topic
- [x] [WojSad] Implement handler for SAS responses
- [x] [WojSad] Implement request merging mechanism
- [x] [Dysproz] Create kubernetes manifests for RabbitMQ deployment

[1]
SSC-Wireless Innovation Forum, “Signaling Protocols and Procedures for Citizens Broadband Radio Service (CBRS): Spectrum Access System (SAS) - Citizens Broadband Radio Service Device (CBSD) Interface Technical Specification”, WINNF-TS-0016-V1.x.x https://winnf.memberclicks.net/assets/CBRS/WINNF-TS-0016.pdf

**Comment by Dysproz** [comment]
PR with _ Implement Python class which handles multiple queues with different requests topics_ : https://github.com/magma/domain-proxy/pull/32

**Comment by Dysproz** [comment]
Starting working on *Create kubernetes manifests for RabbitMQ*

**Comment by Dysproz** [comment]
PR with RabbitMQ k8s manifests: https://github.com/magma/domain-proxy/pull/38

**Comment by Dysproz** [comment]
PR for Create kubernetes manifests for RabbitMQ deployment has been merged

**Comment by tjj-freedomfi** [comment]
development completed for this task - can be closed after finalizing #61
