### ISSUE TITLE
Domain Proxy NMS UI still active when Domain Proxy module is disabled in deployment

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#469]
As reported, the Domain Proxy UI functionality is still active even if domain proxy has been disabled in deployment helm charts.
Please note, Domain Proxy module is disabled by default, and requires manual enabling per environment deployment. However NMS UI implementation for Domain Proxy remains always present.

Suggested options are:
* There is a feature flag mechanism that we were thinking about removing because it is currently not really used. If we use that  one would have to separately enable it on a per organisation basis.
* Probing if Domain Proxy is enabled by hitting some endpoint and hiding disabling the UI if we get an error.
* Somehow persisting whether Domain Proxy is enabled. 

Approach:
Investigate internally if suggestions can be applied and are consistent with similar cases in Magma.
If not, extend discussion to Magma NMS community to figure out best approach.

**Comment by thmsschmitt** [comment]
@xbend It would be good to have this fixed before the 1.8 release otherwise everybody will constantly get those CBSD errors.

**Comment by xbend** [comment]
@thmsschmitt 
Is there a timeline for creating the 1.8 branch? How much time do we have to fix the issue?

**Comment by thmsschmitt** [comment]
That is a question that can be better answered by other people. Let's have this discussion in Slack, I'll raise it in the relevant channel. Imho we could also implement a simple solution first e.g. suppress the error and come up with a proper fix later.

**Comment by Neudrino** [comment]
> Let's have this discussion in Slack

E.g. the [#magma-releases channel](slack://user?team=T018QE9RWKT&channel=C0301NRRL7K) with [this post](https://magmacore.slack.com/archives/C0301NRRL7K/p1658223758200239).

**Comment by Neudrino** [comment]
https://github.com/magma/magma/pull/13428 only provided a temporary mitigation of the problem but not a real fix.

![grafik](https://user-images.githubusercontent.com/13189449/186414941-0b2cc586-284f-4cd8-8565-8033b58384fc.png)

That means, that this issue should be reopened until a proper fix is provided.
