### ISSUE TITLE
CI does not filter pr jobs correctly

### ISSUE THREAD

**Issue by jkmar** [magma/domain-proxy#471]
Recently this pr was merged: https://github.com/magma/magma/pull/13076, but it broke the RC tests, which were not run for that pr.
We should not have such situations and should always run necessary pr jobs.

**Comment by xbend** [comment]
The problem is that Workflow filters for paths, that should be taken into account when selecting individual unit test jobs, are wrong.

For instance, path for Radio Controller code:
`dp/cloud/python/radio_controller/**`
While it should be:
`dp/cloud/python/magma/radio_controller/**`
