### ISSUE TITLE
Implement database schema

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#57]
Create required schema in Magma database
- [x] Add timestamp fields to tables
- [x] Ask about concept or "CBSD registration" within DP
- [ ] Extend current model with CBSD entity and modify relations
- [ ] Depending on "CBSD registration", maybe add SAS operator entity and tie it with CBSD
- [ ] CBSD registration can include optional protocol to use for that CBSD

**Comment by xbend** [comment]
As part of this task, lets initiate a discussion with the Community regarding the pure schema design within Magna (no exact table layouts yet)

**Comment by xbend** [comment]
karthik subraveti  30/06/2021
If it is implemented as storing request/responses, it looks fine. I would ideally prefer CBSDs to be stored instead. Also this doesn't seem entirely consistent with how entities exist in orc8r today. @Hunter Gatewood (FB) posted this today on discussions https://github.com/magma/magma/discussions/7845. I'm not sure if the goal is to completely align these services with orc8r today.
