### ISSUE TITLE
Initiate and maintain state for Active mode

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#68]
DP Requirement ID: **APM-05**

The aggregation and proxy management process in Active mode shall instantiate and maintain two state machines according to [1] on the SAS Client interface and separately on the CBSD Proxy Interface for each CBSD connection.

**Comment by xbend** [comment]
TODO:
Review existing integration test and add extra assertions for state, grants, hearbeats, heartbeat intervals, persistence of state

**Comment by xbend** [comment]
This task has been done. Was part of:
* https://app.zenhub.com/workspaces/magma--domain-proxy-development-6064cb9d84ca0600135548c9/issues/magma/domain-proxy/180
* https://app.zenhub.com/workspaces/magma--domain-proxy-development-6064cb9d84ca0600135548c9/issues/magma/domain-proxy/188
