### ISSUE TITLE
Sketch DP solution architecture

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#7]
The architecture sketch should address those parts:
- [x] [Dysproz, m-trojanowski, WojSad] design the flow of requests between radios and SAS server
- [ ] [Dysproz, m-trojanowski, WojSad] decide the split of particular components into containers
- [x] [m-trojanowski] model HA for particular components
- [ ] [All] decide on the persistency layer (recommendation - Postgre with HA + Redis for particular parts)
- [ ] [All] decide on the schemas in databases
- [ ] [Joey] prepare a mapping table of supported radio interfaces

**Comment by tjj-freedomfi** [comment]
[WiP] LInk to architecture sketch:
https://drive.google.com/file/d/1p5F8vSo0F0vnhcJCXbYEEETP7ylBSHDu/view?usp=sharing

**Comment by Dysproz** [comment]
Sketch with architecture development steps: https://drive.google.com/file/d/1TCxz0Dmixcjp6TU6L7WUYDI5eqxQBAzj/view?usp=sharing

**Comment by tjj-freedomfi** [comment]
Next iteration of the architecture drawing + short descriptions (all to be embedded into the final proposal .md file for Magma community):
https://docs.google.com/document/d/1b-zsVU00dE7wcj9-g2lC_Z_ICI3kOCD96D3er_HkJk8/edit
