### ISSUE TITLE
Setup access to relevant GitHub repos and ZenHub

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#8]
Access to magma/domain-proxy and openEPC/domain-proxy repos and ZenHub in needed for:
- [x] Wojciech Sadowy - WojSad
- [x] Szymon Krasuski - Dysproz 
- [x] Artur Dębski - xbend
- [x] Marcin Trojanowski - m-trojanowski
- [x] Tomasz Jędrośka - tjj-freedomfi

**Comment by 119Vik** [comment]
The team is created and has access to the repo https://github.com/orgs/magma/teams/domain-proxy-developers 
Most of the team members need to be invited into the Org first. Asked @PARitter  to help with invites.

**Comment by ekowtaylor** [comment]
Invites sent to all members, pending acceptance then will add to repos.

**Comment by 119Vik** [comment]
@tjj-freedomfi  just checked the list of members - https://github.com/orgs/magma/teams/domain-proxy-developers/members = seems every one we need so far are in the group
