### ISSUE TITLE
[Spike] Investigate the possibility of getting actual CBSD requests (MitM) 

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#84]

**Comment by m-trojanowski** [comment]
List of requirements to be met in order to run mitm
https://docs.google.com/document/d/1nFH42z3UeUg6xHwbhwqM2jt3qmScHGj1QKvPL8vMwg0/edit?usp=sharing

**Comment by xbend** [comment]
@jpad-freedomfi Please review the requirement list presented by Marcin. We would like to plan next steps depending on what can be met from that list.
