### ISSUE TITLE
CBSD request validation

### ISSUE THREAD

**Issue by xbend** [magma/domain-proxy#85]
All requests received by DP should be validated (JSON validation).

* [x] Modify tests to include checking for request and response contents (format/json, fields, etc)
* [x] Verify request structure (marshmallow?)

**Comment by tjj-freedomfi** [comment]
@jpad-freedomfi what should happen if sent payload is incorrect
CC @xbend @WojSad

**Comment by xbend** [comment]
If request payload is not JSON - return generic HTTP error (5XX)

**Comment by xbend** [comment]
As discussed with Joey on 16/06/2021 - since we are pushing all requests to SAS anyway, we should only handle here malformed HTTP data (something that cannot be serialized as a JSON object).

While full request object validation might be useful in the future - we decided not to write full validation code and only write this when needed (active mode in the future).
