### ISSUE TITLE
[Spike] Support model for different CBSD protocols

### ISSUE THREAD

**Issue by tjj-freedomfi** [magma/domain-proxy#92]
- [x] [Marcin] Check how the traffic can be directed based on the protocol (at least two initial ones in the very beginning)
- [ ] [Artur] Check the coverage of subsequent protocols (apart from Airspan, TR69 which need to be implemented) and decide what other ones we would like to support (the next ones on the list are SNMP and NetConf)
- [ ] [Artur] Discuss the approach with the community (mostly Amar, Karthik and Tariq)
- [ ] [Artur] Prepare the model for extending the solution with additional protocol when needed

**Comment by m-trojanowski** [comment]
Based on discussion on where to obtain traffic from, this task is obsolete. We're getting different protocols traffic from magma components, so no detection is required.

**Comment by xbend** [comment]
There is no need to do protocol detection as only CBSD-SAS protocol will be handled directly by DP.
Other protocols will be implemented as part of `enodebd` within Magma AGW.
